# Generated by Django 5.0.14 on 2026-06-03 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaPerdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('OTRO', 'Otro')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación de extravío')),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Recompensa ofertada')),
                ('estado', models.CharField(choices=[('PERDIDA', 'Perdida'), ('ENCONTRADA', 'Encontrada')], default='PERDIDA', max_length=20, verbose_name='Estado')),
                ('fotografia', models.ImageField(upload_to='mascotas/', verbose_name='Fotografía principal')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Mascota Perdida',
                'verbose_name_plural': 'Mascotas Perdidas',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_avistamiento', models.CharField(max_length=255, verbose_name='Ubicación del avistamiento')),
                ('fecha_avistamiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del avistamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción de cómo y dónde se vio')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='avistamientos/', verbose_name='Foto de evidencia')),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta avistamiento')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='mascotas.mascotaperdida', verbose_name='Mascota avistada')),
            ],
            options={
                'verbose_name': 'Avistamiento',
                'verbose_name_plural': 'Avistamientos',
                'ordering': ['-fecha_avistamiento'],
            },
        ),
    ]
