# Generated by Django 5.0.14 on 2026-06-03 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correo_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo verificado'),
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de 6 dígitos')),
                ('tipo', models.CharField(choices=[('REGISTRO', 'Registro'), ('PASSWORD', 'Recuperar Contraseña')], max_length=20, verbose_name='Tipo de código')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
            },
        ),
    ]
